// Package config defines configuration structures for tgwrapper.
package config

// KeyboardType defines the type of keyboard to display.
type KeyboardType string

const (
	// KeyboardTypeStatic uses buttons defined in the configuration.
	KeyboardTypeStatic KeyboardType = "static"

	// KeyboardTypeDynamic uses buttons generated by a provider function.
	KeyboardTypeDynamic KeyboardType = "dynamic"

	// KeyboardTypeMixed combines static buttons with dynamic buttons.
	KeyboardTypeMixed KeyboardType = "mixed"
)

// KeyboardConfig defines the keyboard configuration for a step or menu.
// Supports static buttons, dynamic generation, and navigation helpers.
type KeyboardConfig struct {
	// Type specifies the keyboard type: static, dynamic, or mixed.
	Type KeyboardType `json:"type" yaml:"type" mapstructure:"type"`

	// Buttons defines static button rows.
	// Each inner array represents a row of buttons.
	Buttons [][]ButtonConfig `json:"buttons" yaml:"buttons" mapstructure:"buttons"`

	// Columns specifies the number of columns for grid layout of dynamic buttons.
	// Defaults to 2 if not specified or <= 0.
	Columns int `json:"columns" yaml:"columns" mapstructure:"columns"`

	// AddBack adds a back button to return to the previous step.
	AddBack bool `json:"add_back" yaml:"add_back" mapstructure:"add_back"`

	// AddMain adds a main menu button to return to the main menu.
	AddMain bool `json:"add_main" yaml:"add_main" mapstructure:"add_main"`

	// AddCancel adds a cancel button (functionally same as back).
	AddCancel bool `json:"add_cancel" yaml:"add_cancel" mapstructure:"add_cancel"`

	// Provider is the name of a registered function that provides dynamic button data.
	// Required when Type is "dynamic" or "mixed".
	Provider string `json:"provider" yaml:"provider" mapstructure:"provider"`

	// ProviderArgs specifies keys from conversation data to pass to the provider.
	ProviderArgs []string `json:"provider_args" yaml:"provider_args" mapstructure:"provider_args"`

	// CallbackPrefix is prepended to dynamic button callback data.
	// Useful for routing callbacks to the correct handler.
	CallbackPrefix string `json:"callback_prefix" yaml:"callback_prefix" mapstructure:"callback_prefix"`

	// BackText customizes the back button text.
	BackText string `json:"back_text" yaml:"back_text" mapstructure:"back_text"`

	// MainText customizes the main menu button text.
	MainText string `json:"main_text" yaml:"main_text" mapstructure:"main_text"`

	// CancelText customizes the cancel button text.
	CancelText string `json:"cancel_text" yaml:"cancel_text" mapstructure:"cancel_text"`

	// Inline specifies whether to use inline keyboard (default true).
	// If false, uses reply keyboard instead.
	Inline *bool `json:"inline" yaml:"inline" mapstructure:"inline"`

	// OneTime makes the reply keyboard disappear after use.
	// Only applies when Inline is false.
	OneTime bool `json:"one_time" yaml:"one_time" mapstructure:"one_time"`

	// Resize enables auto-resize for reply keyboard.
	// Only applies when Inline is false.
	Resize bool `json:"resize" yaml:"resize" mapstructure:"resize"`
}

// IsInline returns true if this is an inline keyboard.
// Defaults to true if Inline is nil.
func (k *KeyboardConfig) IsInline() bool {
	if k.Inline == nil {
		return true // Default to inline keyboard
	}
	return *k.Inline
}

// GetColumns returns the number of columns for grid layout.
// Returns 2 as default if not specified or invalid.
func (k *KeyboardConfig) GetColumns() int {
	if k.Columns <= 0 {
		return 2
	}
	return k.Columns
}

// GetBackText returns the text for the back button.
// Returns a default emoji text if not customized.
func (k *KeyboardConfig) GetBackText() string {
	if k.BackText == "" {
		return "◀️ Back"
	}
	return k.BackText
}

// GetMainText returns the text for the main menu button.
// Returns a default emoji text if not customized.
func (k *KeyboardConfig) GetMainText() string {
	if k.MainText == "" {
		return "🏠 Main Menu"
	}
	return k.MainText
}

// GetCancelText returns the text for the cancel button.
// Returns a default emoji text if not customized.
func (k *KeyboardConfig) GetCancelText() string {
	if k.CancelText == "" {
		return "❌ Cancel"
	}
	return k.CancelText
}

// NeedsDynamicData returns true if the keyboard requires dynamic button data.
func (k *KeyboardConfig) NeedsDynamicData() bool {
	return k.Type == KeyboardTypeDynamic || k.Type == KeyboardTypeMixed
}
